/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_init;

import Scenarios.Scenario;
import database.SqliteDatabase;

public class App {
	private static String testFileLoc = "C:\\eclipse\\work_space\\capstone\\capstone-project-conspicuous\\gradle_init\\src\\main\\resources\\databases";
	private static String testFileName = "TestFile.rtf";

	public static void main(String[] args) {
		SqliteDatabase sqliteDB = new SqliteDatabase("filesDb.sqlite");
		Scenario sc = new Scenario(testFileName, testFileLoc);
		sqliteDB.getScenarioTable().createScenariosTable();
		sqliteDB.getScenarioTable().insertScenarios(sc);

		String sql = "SELECT * FROM scenarios";
		sqliteDB.getScenarioTable().selectDb(sql);

		// sc.retrieveFile(sqliteDB, sql, testFileName);
	}
}
