/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_init;

import Scenarios.Scenario;
import database.SqliteDatabase;

public class App {

	private static String testFileName = "scenario1.txt";

	public static void main(String[] args) {
		SqliteDatabase sqliteDB = new SqliteDatabase("filesDb.sqlite");
		Scenario sc = new Scenario(testFileName);
		sqliteDB.getScenarioTable().createScenariosTable();
		sqliteDB.getScenarioTable().insertScenarios(sc);

	}
}
